//subscribers
Meteor.subscribe("actors");
Meteor.subscribe("competitions");
Meteor.subscribe("groups");
Meteor.subscribe("matches");
Meteor.subscribe("points");
Meteor.subscribe("predictions");
Meteor.subscribe("questions");
Meteor.subscribe("results");
Meteor.subscribe("userinfo");
